import { car } from "../../types/transport/Auto/ICarNew"

export const carNewForm: car = {
  brand: null,
  vehiclePassport: null,
  inspectionData: null,
  color: null,
  description: null, 
  meetingPoint: null,
  tags: [], 
  name: null,
  photo: null, 
  price: null,
  video: null,
  VIN: null,
  additionalOptions: {
    powerSteering: null,
    climatControl: {select: null, checkbox: null},
    salon: {select: null, checkbox: null},
    heating: null,
    powerWindows: null,
    electricDrive: null,
    settingsMemory: null,
    drivingAssistance: null,
    antiThiefSystem: null,
    airbags: null,
    activeSafety:  null,
    multimedia: null,
    audioSystem: {select: null, checkbox: null},
    headlights: {select: null, checkbox: null},
    tiresWheels: {select: null, checkbox: null},
  },
}